.circleci/config.yml

These two seem not to be needed.  I'm guessing that `python3-pip` has some version of `python3` as a dependency already.

CI: remove unneeded rpms

---

src/ChcGraph.cc
src/ChcGraph.h
src/ChcInterpreter.cc
src/TermUtils.h
src/Validator.cc
src/Validator.h
src/Witnesses.cc
src/Witnesses.h
src/engine/Bmc.cc
src/engine/Bmc.h
src/engine/Engine.h
src/engine/Kind.cc
src/engine/Kind.h
src/engine/Lawi.cc
src/engine/Lawi.h
src/engine/Spacer.cc
src/engine/Spacer.h
src/engine/TPA.cc
src/engine/TPA.h
src/transformers/NonLoopEliminator.cc
src/transformers/SimpleChainSummarizer.cc
src/transformers/Transformer.h
test/TestTemplate.h
test/test_BMC.cc
test/test_KIND.cc
test/test_LAWI.cc
test/test_Spacer.cc
test/test_TPA.cc
test/test_Transformers.cc

As a preparation for producing witnesses for nonlinear systems (from Spacer engine), we change the format of the invalidity witness. The new style is similar to what Eldarica prints out. The proof is a sequence of steps where each step is a derived fact (instantiation of an uninterpreted predicate with constants as the arguments). Moreover, we remember the indices for the premises of each derivation step and the edge that was used for this derivation step.
The validator has been updated to validate this new format. It also meant that we removed the distinction between Graph- and System- invalidity witness.
Unfortunately, we now require the corresponding ChcDirectedHyperGraph to validate InvalidityWitness, which means that we have to keep around a copy of the original graph, if we are …

Witnesses: Simplify invalidity witnesses

---

src/Validator.cc
src/Witnesses.h
src/engine/Spacer.cc
src/engine/Spacer.h
src/transformers/SimpleChainSummarizer.cc
test/test_Spacer.cc
test/test_Transformers.cc

Previously, we did not have a way to produce a proof of unsatisfiability from the Spacer engine.
I thought of two possibilities: either log the proof obligations, building the proof from bottom to leaves, or log the must summaries, building the proof from leaves to bottom.
I decided to go for the latter, since it seems like less bookkeeping. For each must summary, we now also remember what were its premises, i.e., from which constrained predicates and using which edge we can derive the current must summary (constrained fact in current node). This is almost the same as our proof format, but not quite. Single must summary can cover a large set of states, in the proof format we want to pick single state.
We solve this by post-processing the database of must summaries to pick for each one a …

Spacer: Implement logging of the unsatisfiability proof

---

src/engine/Spacer.cc

When checking reachability of a proof obligation, we first check
reachability with must summaries and then unreachability with may
summaries. If both checks fails, then we systematically iterate over
vertices to find the first one which makes reachability feasible when
may summary is used instead of the must summary.
For edges with single source this unnecessarily duplicates work, because
when we fail to prove unreachability with may summaries, we already have
the model to generate proof obligation at that point, so we do not need
to repeat the same check later.

Spacer: Do not repeat work when checking edges with single source

---

src/CMakeLists.txt
src/graph/ChcGraph.cc
src/graph/ChcGraph.h
src/transformers/CommonUtils.cc
src/transformers/CommonUtils.h
src/transformers/NonLoopEliminator.cc
src/transformers/NonLoopEliminator.h
src/transformers/SimpleChainSummarizer.cc
test/test_TPA.cc

This adds the missing backtranslation of proofs (invalidity witnesses) for NonLoopEliminator transformation.

Transformers: Proof backtranslation for node elimination

---

src/CMakeLists.txt
src/ChcInterpreter.cc
src/graph/ChcGraph.cc
src/graph/ChcGraph.h
src/transformers/BasicTransformationPipelines.h
src/transformers/NodeEliminator.cc
src/transformers/NodeEliminator.h
src/transformers/NonLoopEliminator.cc
src/transformers/NonLoopEliminator.h
src/transformers/SimpleChainSummarizer.cc
src/transformers/SimpleChainSummarizer.h
test/test_Transformers.cc

This generalizes NonLoopEliminator to a pass that eliminates, by contraction, all nodes accepted by a specified predicate.
With this, we re-use all the functionality to create a simplification pass that eliminates all non-looping nodes, without hyperedges, and with at most one incoming or outgoing edge.
Contracting such nodes does not increase the number of edges (in fact it decreases the number by one).
The simplification seems beneficial on CHC-COMP benchmarks.

Generalize NonLoopEliminator and add new simplification pass

---

src/engine/TPA.cc
test/test_TPA.cc

When backtracking from a target TS to a source TS, after the (previously) truly reached in the source has been blocked, we compute a new set of truly reached states in the source. Then we want to check the edge again to the target.
However, at this point, we were trying the INITIAL states of the target's TS. This is not correct, because we have not updated the initial states of the TS before, we have only updated the truly safe states, which is exactly what should be considered at this point. We want to know if from the truly reached of source TS we can reach something that is NOT truly safe in the target TS.

TPA: Fix bug in the analysis of transition-system chain

---

src/engine/TPA.cc
src/engine/TPA.h
test/test_TPA.cc

If TPA was queried with a transition system that has empty bad states, it ran into an assertion that the interpolant is not logical true. This assertion is, in general, useful to detect incorrect behaviour of the algorithm, so we would like to keep it, even though in this special case of `query == false` such interpolant is correct. Instead, we check for these special cases beforehand.
For now we only make syntactic check. It is possible we should do proper SMT check on the initial and query states.

TPA: Handle properly special cases of trivial transition systems

---

src/Witnesses.cc

We were missing the quotes around the names of the predicates, which may be required for weird names, for example with spaces.
Fixes #27

Witness: Fix printing predicate names in model

---

src/Witnesses.cc
src/Witnesses.h
src/engine/Bmc.cc
src/engine/Bmc.h
src/engine/IMC.cc
src/engine/IMC.h
src/engine/Kind.cc
src/engine/Kind.h

This refactoring prepares the code for transformation of general linear CHC system to a transition system. The plan is that there will be no CHC graph corresponding to a transition system, but we go to directly to our inner TS representation. For this reason, we refactor the methods so they do not require both representation of a transition system.
To support witness production, we add a simple wrapper for a witness for our inner TS representation.

Engines: Refactor computation of witnesses for transition systems

---

.clang-files
src/ChcInterpreter.cc
src/Witnesses.h
src/engine/Common.cc
src/engine/IMC.cc
src/engine/IMC.h
src/engine/Kind.cc
src/engine/TPA.cc
src/graph/ChcGraph.cc
src/graph/ChcGraph.h
src/transformers/MultiEdgeMerger.cc
src/transformers/MultiEdgeMerger.h
src/transformers/SingleLoopTransformation.cc
src/transformers/SingleLoopTransformation.h
src/transformers/Transformer.h
test/test_IMC.cc
test/test_Spacer.cc
test/test_Transformers.cc

The main change here is a fix to IMC to produce correct inductive invariant for the given transition system.
The problem was that when IMC detects a fixed point, the state formula is an inductive invariant, but it is not necessarily safe on its own. We only know that it cannot reach bad states in `k` steps where `k` is the current value of the parameter of the procedure `finiteRun`.
While this is sound, because it still guarantees that bad states are unreachable, the witness has to be different.
For now I only was able to prove that the fixed point conjoined with the negation of bad states is k-inductive.
(It would be good to try to improve on this to avoid k-induction).
While working on this, I discovered a bug in `BackTranslator` for `NodeEliminator` which was not tracking the necessary …

Fix issues with witnesses for IMC and some transformation passes

---

.circleci/config.yml

This follows the suggestion at https://circleci.com/docs/using-macos/,
following the deprecation announcement: https://discuss.circleci.com/t/macos-resource-deprecation-update/46891

CI: Update MacOS image in CircleCI configuration

---

src/engine/TPA.cc
src/engine/TPA.h

In the current version method TPABase::getSafetyExplanation does not work correctly if the safety has been proven using (left or right) transition invariants collected in the Houdini check.
The problem is that the method in the current version still relies on the information stored in explanation.power, but this information is not (and cannot) be filled in the case mentioned above.
The proposed solution is to store directly the transition invariant in the explanation, instead of implicitly relying on the assumption that the invariant is one of the abstract transitions.

TPA: Fix computation of explanations

---

.clang-files
src/CMakeLists.txt
src/QuantifierElimination.cc
src/Validator.cc
src/Witnesses.cc
src/engine/Bmc.cc
src/engine/Common.cc
src/engine/Engine.h
src/engine/IMC.cc
src/engine/Kind.cc
src/engine/Lawi.cc
src/engine/Spacer.cc
src/engine/TPA.cc
src/transformers/CommonUtils.cc
src/transformers/MultiEdgeMerger.cc
src/transformers/SimpleChainSummarizer.cc
src/transformers/SingleLoopTransformation.cc
src/transformers/TrivialEdgePruner.cc
src/utils/SmtSolver.cc
src/utils/SmtSolver.h

The goal is to provide a simple abstraction over OpenSMT's solver so that we do not have to repeat unnecessary complicated setup of OpenSMT's SMTConfig and MainSolver. It would also better contain future changes in OpenSMT.
In the future, this abstraction can be extended to completly isolate OpenSMT's solver in a single place.

Everywhere: Simplify typical use of SMT solver

---

src/graph/ChcGraph.cc
src/graph/ChcGraph.h
src/transformers/CommonUtils.cc
src/transformers/CommonUtils.h
src/transformers/NodeEliminator.cc
test/test_Transformers.cc

This change extends SimpleNodeEliminator so it also eliminates nodes with single incoming simple edge and any number of outgoing (hyper)edges.
Previously, a node was not eliminated if it participated in a hyperedge.
The proposed change leads to more nodes eliminated in some benchmarks of CHC-COMP, which helps the Spacer engine on nonlinear systems.
Additionally, some nonlinear systems can be translated to linear ones by this transformation, enabling other engines to solve some nonlinear benchmarks.

SimpleNodeEliminator: Allow restricted elimination of nodes with hyperedges

---

src/engine/TPA.cc
test/test_TPA.cc

The conjunction of constraints(which was used previously), restricted the paths which should not've been restricted, leading to the spurious SAFE results.
- Conjunction was replaced with disjunction, therefore as long as at least one branch is reachable from the end of TS, we still should consider the node as a potential candidate.
- Two tests are added to validate this specific property.

DAG-disj: Fixed conjunction to disjunction in "addRestrictions"

---

src/ModelBasedProjection.cc
src/transformers/ConstraintSimplifier.cc
test/test_MBP.cc

This PR introduces fixes for two problems.
One is a corner case in model-based projection where a presence of ~false literal would cause incorrect computation of extended model when handling divisibility constraints.
After this fix, proof production on the same example showed that after the recent changes in the normalization process we no longer version auxiliary variables introduced during elimination of ITE/DIV/MOD operators.
The proposed change here is to version those variables immediately after their creation.

Fix incorrect behaviour detected on a test case

---

src/Witnesses.cc
src/proofs/ProofSteps.cc
src/proofs/ProofSteps.h
src/proofs/Term.cc
src/proofs/Term.h

Investigation into a performance issues on some CHC-COMP benchmarks revealed that every access to the steps computed by the `CongChainVisitor` created a new copy of the steps, which was a performance killer, since this actually happened on access to each step. The easy fix here is to return (and use) just a reference to the stored vector of steps.
Additionally we make use of a C++ [`std::enable_shared_from_this`](https://en.cppreference.com/w/cpp/memory/enable_shared_from_this) that allow us to still use the visitor pattern, but turn the raw pointer back to shared pointers without the risk of creating two separate `shared_ptr` managing the same raw pointer. Since we only create `Term`s as shared pointers, this is safe, but we should make another step and hide all constructors and only …

Performance optimizations and small cleanup in Alethe proof production

---

src/TermUtils.h
src/graph/ChcGraph.cc
src/graph/ChcGraph.h

When contracting a vertex with an incoming edge that has auxiliary
variables, we have to be careful not to end up with the same auxiliary
variable in the labels of multiple edges. This could cause problems when
considering paths containing such edges, because we could end up with a
name clash.
The current fix is to rename auxiliary variables when this potential
clash could occur.
In the future we should rethink our versioning strategy, possibly
enforce stronger invariants that would prevent this scenario in the
first place.
Fixes #51.

Graph: More carefule node elimination

---

src/proofs/Term.cc
test/prooftesting/negative_mod.smt2

The semantics of the modulo operation on OpenSMT's FastRationals is different than the semantics of modulo as defined by SMT-LIB. This commit changes the evaluation of a modulo operation on two integers to follow the SMT-LIB semantics.
Fixes #55.

Alethe: Fix evaluation of modulo operation

---

src/TermUtils.cc
src/Witnesses.cc

The method Logic::printTerm computes string representation of a term by
recursively computing string representation of its arguments. This is
not efficient in a DAG term when a subterm is reachable on multiple
paths, because such a subterm would be stringified multiple times, one
per each path. Instead, we use our helper method that uses let terms for
conjunctions and disjunctions.
This method could be optimized to introduce let only for subterms
reachable by more than one path, but we leave that as future work.
Fixes #54.

Make model output more compact

---

src/transformers/SingleLoopTransformation.cc
test/test_TPA.cc

In the current encoding to single transition system, when translating edge constraint, we do not put any restriction on the big system's state variables that do no correspond to the variables of the target node. This means that when we encounter alien variables during backtranslation of validity witness, we can universally quantify these variables to obtain predicate representation only over its arguments. We can then apply quantifier elimination.
Since QE works on existential quantifiers, we have to first negate the original invariant and then negate again after QE.
Fixes #45.

SingleLoopTransform: Deal with alien variables in validity witnesses in backtranslation

---

src/proofs/ProofSteps.cc
test/prooftesting/predicate_without_args.smt2

The changes in #62 broke proofs for systems with nullary predicates. This PR fixes handling of this case.
Moreover, it uses simpler rule to derive one side of an equivalence from the equivalence itself and the other side.

Alethe: Fix handling of nullary predicates

---

.circleci/config.yml

CircleCI is shutting down its Intel-based OSX images and moving to M1-based images. See: https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718

CI: Update OSX resource

---

.circleci/config.yml

CentOS 7 is no longer suppoerted, so we have replaced StarExec images with Fedora

CI: Replace starexec images with Fedora

---

src/Options.cc
src/Options.h
src/engine/Bmc.cc
src/engine/Bmc.h

We introduce an option to solv linear systems in BMC without first converting them to a transition system.
The idea for the implementation is the following.
We unroll the CHC system and keep track if we can reach node V in level L. We collect all such reachable nodes in a frontier and in each step compute the next frontier. Before a node is included in the next frontier, we check if it can truly be reached. We introduce only one version of the node, even if it can reached by multiple paths. Furthermore, we include the conditions that of a node V has been reached in level L, then one of the successors of V has to be reached in level L+1. Similarly, we include the conditions that if node V has been reached in level L+1, then one of its predecessors must have been reached in level L.
The …

BMC: Support linear CHC system directly

---

.clang-files
src/Options.cc
src/Options.h
src/engine/Bmc.cc
src/engine/Bmc.h

This is inspired by the implementation in Z3.
The main idea is that we only need to assert that if we reach some node
in step l+1, then we must have used one of the incoming edges (clauses
where this node is a head) and we must have been in the source of the
edge in step l.
(We also assert that we start at entry at step 0.)
Then we check for each step if we can be in the exit node.
These conditions are sufficient, we do not need the constraints about
forward reachability (if I am at some node then I need to be in one of
its successors in the next step).

BMC: Simplify and improve the algorithm for solving general linear systems

---

.clang-files
src/engine/ArgBasedEngine.cc
src/utils/StdUtils.h
test/test_PredicateAbstraction.cc

After predicate refinement, instead of starting to build the ART from scratch, we keep the current one, but update it to reflect the new set of predicates.
This means that we have to check for each node if the newly added predicates are true in that node or not (this needs to be done in the order that guarantees that parents are refined before the children).
Since we are currently building abstract reachability tree and not graph, we have to maintain the set of covered nodes (to prevent explosion). The covering relations has to be checked because refinement may have invalidated some coveree-coverer pairs.
NOTE: In case we switch from ART to ARG (which may be more efficient), refinement would have to be very differently.
In case a node has more than one incoming edge, some new predicate …

Predicate abstraction: Proper refinement of the abstract reachability tree

---

.circleci/config.yml
.clang-files
README.md
src/CMakeLists.txt
src/Options.cc
src/engine/DAR.cc
src/engine/DAR.h
src/engine/EngineFactory.cc
test/CMakeLists.txt
test/test_DAR.cc

The implementation follows the description in the TACAS 2013 paper
[Intertwined Forward-Backward Reachability Analysis Using Interpolants](https://link.springer.com/chapter/10.1007/978-3-642-36742-7_22).
Initial experiments suggest reasonably good performance on LRA-TS
benchmarks from CHC-COMP.

First version of the algorithm Dual Approximated Reachability

---

.clang-files
src/CMakeLists.txt
src/Options.cc
src/Options.h
src/TransformationUtils.cc
src/engine/TPA.cc
src/graph/ChcGraph.cc
src/graph/ChcGraph.h
src/transformers/CommonUtils.h
src/transformers/NestedLoopTransformation.cc
src/transformers/NestedLoopTransformation.h
test/test_Transformers.cc

This is an implementation of the merging of the nested loops into a single Transition System. It is done via the same approach as the transformation of the whole instance into the single System, but is adapted to only merge loops in the Graph structure into a single node.

TPA: Merge DAG nested loops

---

src/engine/TPA.cc
src/engine/TPA.h

In the [FM'24 paper](https://link.springer.com/chapter/10.1007/978-3-031-71162-6_29) we came up with much nicer description of how the algorithm on DAG of transition systems works.
Here we rewrite the algorithm to match that description.
The two phases, moving along an edge from one TS to another and traversing one TS, are clearly distinguished.

TPA: Rewrite the DAG-handling algorithm

---

src/engine/ArgBasedEngine.cc
test/test_PredicateAbstraction.cc

This PR includes a few improvements of the PA engine.
- Unsatisfiability proof is created as a DAG, not a tree: The proof is much more compact and in line with how other engines create it.
- Interpolants are simplified before used as predicates: Interpolants from proofs are typically very redundant. Since we use them repeatedly in further checks, it pays off to simplify them as much as possible beforehand.
- Covering relation is based on subsumption (set inclusion) instead of equality of the satisfied predicate sets.
- Refinement procedure is fixed and improved: When refining ARG after refuting spurious CEX we only check for predicates that were not satisfied before. Also, when some parent of a node has changed, we also need to re-check the child node, because some of the predicates that …

Predicate Abstraction: Various improvements to improve performance

---

src/TransitionSystem.cc
src/TransitionSystem.h

The computation only needs interpolation, not quantifier elimination, it is based on the analysis of reinforced unfold transformation from the 2015 paper [Horn Clause Solvers for Program Verification](https://link.springer.com/chapter/10.1007/978-3-319-23534-9_2).

More efficient computation of inductive invariants from k-inductive ones

---

src/graph/ChcGraph.cc
src/transformers/NodeEliminator.cc
test/test_Transformers.cc

Previously, we detected auxiliary variables in an edge's label simply by checking the names of the variables.
However, this is not reliable, because preprocessing passes can create new edges where previously state variables are now auxiliary. Since we do not rename such variables at the moment, we need more precise check if a variable is auxiliary or not.
Additionally, we need to rename auxiliary variables in more cases than previously thought.
Fixes #99.

Graph: Fix computation of auxiliary variables in edge's label

---

src/graph/ChcGraph.cc
src/graph/ChcGraph.h
test/test_Transformers.cc

Instead of trying to guess when variable renaming is necessary, and trying to rename variables before edge merging, a better solution is simply to rename auxialiary variables when a new edge is created (as part of edge merging).
NOTE: We could improve auxiliary variable elimination here. Currently, the elimination is only based on extracting substitutions, but it does not detect, for example, that an auxiliary variable is redundant and could be removed.
Fixes #101.

NodeEliminator: Rename auxiliary variables preemptively

---

src/TransformationUtils.cc
src/graph/ChcGraph.cc
src/transformers/RemoveUnreachableNodes.cc
src/transformers/RemoveUnreachableNodes.h

Fixes the check if a graph is trivial.
`RemoveUnreachableNodes` now detects the case if there is no outgoing edge from `true` (there are no facts in the system).
`ChcDirectedGraph::getVertices` now properly returns all vertices and in sorted order.
Fixes #103.

Graph: Small fixes in various utility methods

---

src/transformers/RemoveUnreachableNodes.cc

`RemoveUnreachableNodes` transformation previously only detected nodes that were not backward-reachable from false.
Now we also detect nodes that are not forward-reachable from true and prune those as well.

Transformations: Prune also nodes unreachable from true

---

src/CMakeLists.txt
src/ChcInterpreter.cc
src/graph/ChcGraph.cc
src/graph/ChcGraph.h
src/transformers/EdgeInliner.cc
src/transformers/EdgeInliner.h
test/test_Transformers.cc

Edge inlining refers to a transformation where we detect if an edge has at most one feasible predecessor.
If there is no feasible predecessor, the edge can be safely removed from the graph, without affecting reachability.
If there is a single feasible predecessor, the edge can be merged with the predecessor. We can remove the original edge but must keep the predecessor, because there might be other outgoing edges from the original edge's source.
We also do not want to inline if the predecessor is a loop. That would basically meant peeling off one iteration from the loop, and that could continue for a long time.
By feasibility we mean that the conjunction of the labels of the edge and its predecessor (after appropriate variable renaming) is satisfiable.
However, we do not check …

Preprocessing: First version of edge inlining 

---

src/CMakeLists.txt
src/ChcInterpreter.cc
src/transformers/BasicTransformationPipelines.cc
src/transformers/BasicTransformationPipelines.h
test/test_Transformers.cc

We have noticed a few times that after the default preprocessing, nodes that could be eliminated by `SimpleNodeEliminator` were still present in the graph, probably because some nodes become "simple" only after the run of `MultiEdgeMerger`.

Preprocessing: More node eliminations in the default pipeline

---

src/Validator.cc
src/Witnesses.cc
src/Witnesses.h
src/engine/Common.cc
src/engine/TPA.cc
src/transformers/NodeEliminator.cc
src/transformers/SimpleChainSummarizer.cc
src/transformers/SingleLoopTransformation.cc
test/test_Transformers.cc

Previously, chain summarizer would summarize (contract) an entire loop if it consisted of simple edges.
While this may be OK, the backtranslator does not work correctly in this case.
The solution is to not summarize the entire loop, but skip one edges, thus forming proper simple chain.
The last node can be processed by node eliminator correctly.

Preprocessing: Fixing issues with chain summarizer

---

src/engine/PDKind.cc
src/engine/PDKind.h
src/utils/ScopeGuard.h

The main change in PDKIND here is to use one solver for the push method incrementally, which avoids quite a lot of repetitive work.
We also use init solver in reachability checks incrementally.
Apart from that, the implementation is refactored to create better (code) abstraction.

PDKIND: Cleanup and improvements

---

src/engine/Kind.cc
src/transformers/BasicTransformationPipelines.cc
src/transformers/NodeEliminator.cc
src/transformers/NodeEliminator.h
test/test_Transformers.cc

I believe the rationale for for this transformation was to get as close to a transition system (or DAG of transition systems) as possible. However, trying to eliminate all non-looping nodes can lead to an explosion in the number of edges, and sometimes even this transformation itself does not finish. For example, if a node has more than 1000 incoming and outgoing edges it would have to create more than 1 000 000 edges to eliminate such a node.

Preprocessing: Do not try to eliminate all non-loop nodes

---

src/CMakeLists.txt
src/engine/DAR.cc
src/engine/DAR.h
src/engine/Engine.h
src/engine/IMC.cc
src/engine/IMC.h
src/engine/Kind.cc
src/engine/Kind.h
src/engine/PDKind.cc
src/engine/PDKind.h
src/engine/TPA.cc
src/engine/TPA.h
src/engine/TransitionSystemEngine.cc
src/engine/TransitionSystemEngine.h
test/test_Transformers.cc

Engines that operate on transition system shared the code how to get to a transition system from `CHCDirectedHyperGraph`.
We refactor that code to a common superclass, while still allowing engines to customize individual steps of the transformation.

Engines: Unify first phase of engines that operate on transition systems

---

src/engine/ArgBasedEngine.cc
src/engine/Spacer.cc
src/utils/SmtSolver.cc
src/utils/SmtSolver.h

We reuse the same functionality we are already using in Spacer.
The results are somewhat mixed.
It seems the checks can be harder than when the lemmas are checked one by one.
We could experiment further by recursively splitting the formulas being checked and only perform the current method on small sets of formulas.

PA: Use batched processing in entailment checks

---

src/TransformationUtils.cc
src/TransformationUtils.h
src/engine/Kind.cc

K-induction checks, as implemented, require satisfiability checks where the init and query states are negated.
If they would contain auxiliary variables, these would have to be universally quantified in the negations.
Treating them as existentially quantified changes the meaning of the checks. For this reason, we need to fully eliminate auxiliary variables from Init and Query in the KIND engine.
This basically reverts the change made in 9811d3a for KIND, but keeps it for other engines where the same issue does not apply.

KIND: Init and query must not contain auxiliary variables

---

src/engine/TPA.cc

Current implementation of the algorithm assumes that there are no auxiliary variables in init and query.
We need to check where exactly this is needed and see if we can relax this restriction.

TPA: Init and query must not contain auxiliary variables

---

.clang-files
README.md
src/CMakeLists.txt
src/Options.cc
src/TermUtils.cc
src/TermUtils.h
src/bin/golem.cpp
src/engine/EngineFactory.cc
src/engine/SymbolicExecution.cc
src/engine/SymbolicExecution.h
test/CMakeLists.txt
test/test_QE.cc
test/test_SymbolicExecution.cc

Based on [this paper](https://link.springer.com/chapter/10.1007/978-3-031-50524-9_13), we implement a *forward* exploration of the reachability graph by representing the reachable states precisely by their path formula.
To keep the formula compact and increase the chance of identifying same states, we apply light-weight quantifier elimination to the (implicitly existentially quantified) non-current-states variables.
SAT witnesses are computed the same way as in predicate abstraction: we need to disjoin all discovered states associated with the given predicate. However, note that we need to compute representation only over current state variables, so we need to apply full quantifier elimination here.
For UNSAT witness, we need to be able to reconstruct the path for the given node in …

Engines: Add new engine based on forward symbolic execution

---

src/engine/ArgBasedEngine.cc
src/utils/SmtSolver.cc
src/utils/SmtSolver.h

This was the strategy some time ago, but then it was changed between versions 0.6.4 and 0.6.5, to unify it with the strategy used in Spacer. However, it seems this strategy has negative effect on the performance of PA on LRA-TS benchmarks.
We will need to search for the best strategy here, but for now we revert to the previous implementation of the entailment check in PA.
Quick check shows that this is better for LRA-TS, but also for LIA and LIA-Lin benchmarks from 2024 (although some benchmarks exhibit slowdown, the overall effect of this change is positive).
Fixes #130.

PA: Check entailment of a set of formulas one by one

---

src/TermUtils.h
src/engine/ArgBasedEngine.cc
src/graph/ChcGraph.cc
src/graph/ChcGraph.h
src/transformers/CommonUtils.cc
src/transformers/ConstraintSimplifier.cc

Previously, we were manually keeping counts for each occurence of a predicate among the sources.
This is somewhat error-prone.
We already have a mechanism to correctly version the terms of edge sources in the graph, so we just expose this functionality. Here we return a vector of the source terms.
Instead of allocating a vector, we could expose a way to iterate over the source terms an apply a given action to each.

Graph: Add helper to get properly versioned source terms

---

src/TermUtils.cc
test/test_QE.cc

Previously, we could have lost some information about the state variables. For example, if an array access uses an auxiliary variable that is known to be equal to a shifted state var through another auxiliary variable.
After substitutions, the constraint is simplified to true, so all the information is in the substitutions.
Suppose we have these substitutions:
s1[a2] -> 1
a2 -> a1
s2 -> a1 - 1
When we try to eliminate auxiliary variables a1 and a2, we figure out that we can ignore a2, and we can eliminate a1 by reversing the last substitution to a1 -> s2 + 1.
However, at the end, we have to bring back the equality s1[a2] = 1. Since we brought a2 back, we have to re-apply the substitutions. But note that just re-applying the original substitutions does not work, since we would replace a2 …

Fix trivial quantifier elimination in the presence of arrays

---

src/TransformationUtils.cc
src/TransformationUtils.h
src/engine/PDKind.cc
src/engine/PDKind.h
src/engine/TransitionSystemEngine.cc
src/engine/TransitionSystemEngine.h
test/test_PDKIND.cc

After we allowed auxiliary variables in init and query, we encountered auxiliary variables present in the definitions of predicates in the model. Such variables would have to be existentially quantified for the model to be correct, but we don't support that.
In any case, the question whether or not an algorith can handle auxiliary variables in init adn query is more complicated than it originally seemed. For that reason we now mostly revert the implemented change. We still allow auxiliary variables in the *definition* of transition system, but the engines still eliminate them from init and query.  For PDKIND, I believe auxiliary variables in init are OK, so we only eliminate them from the query. For other engines, the question needs to be revisited later.

Engines: Fix dealing with auxiliary variables in transition systems

---

src/termination/Frontend.cc

Previously, we assumed that all terms are given as tuples. However, we should allow 0-ary terms to be just atoms, instead of 1-tuples.

Termination: Parse 0-ary locations correctly

---

src/TransitionSystem.cc
src/TransitionSystem.h

Based on the advice of Prof. McMillan, the computation of 1-inductive invariant can be done with a single query using sequence interpolants. Compared to the previous approach, we need fewer queries (1 vs log k), but we compute more interpolants (k vs log k).
In general the new approach is significantly faster, but there are some cases where the validation of the resulting 1-inductive invariant is slower.
It would be interesting to compare translation + validation time of both approaches.

K- to 1-inductive invariant with sequence interpolants

---

src/engine/TPA.cc
src/engine/TPA.h

TPA engine has a method to reset it to solve a new transition system. However, this has never been used before in an incremental way. It actually did not clear the engine completely, it kept around the reachability solvers. Thus, trying to reset it with a new transition system did not work correctly, because the reachability solvers were kept from previous use.
Here we make sure the solvers are also cleared on a reset.
Fixes #148.

TPA: Fix engine reset
